-- Oracle CDC 전용 계정 생성
-- sqlplus system/system@10.1.5.18:1521/oracle19c @oracle_cdc_user.sql

-- 1. CDC 전용 사용자 생성
CREATE USER cdcuser IDENTIFIED BY cdcpass123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- 2. 기본 권한
GRANT CONNECT TO cdcuser;
GRANT RESOURCE TO cdcuser;
GRANT CREATE SESSION TO cdcuser;

-- 3. CDC 필수 권한
GRANT SELECT ANY TRANSACTION TO cdcuser;
GRANT SELECT ON V_$ARCHIVED_LOG TO cdcuser;
GRANT SELECT ON V_$LOG TO cdcuser;
GRANT SELECT ON V_$LOGFILE TO cdcuser;
GRANT SELECT ON V_$DATABASE TO cdcuser;
GRANT SELECT ON V_$THREAD TO cdcuser;
GRANT SELECT ON V_$PARAMETER TO cdcuser;
GRANT SELECT ON V_$NLS_PARAMETERS TO cdcuser;
GRANT SELECT ON V_$TIMEZONE_NAMES TO cdcuser;
GRANT SELECT ON V_$TRANSACTION TO cdcuser;
GRANT SELECT ON V_$CONTAINERS TO cdcuser;
GRANT SELECT ON ALL_INDEXES TO cdcuser;
GRANT SELECT ON ALL_OBJECTS TO cdcuser;
GRANT SELECT ON ALL_TABLES TO cdcuser;
GRANT SELECT ON ALL_USERS TO cdcuser;
GRANT SELECT ON ALL_CATALOG TO cdcuser;
GRANT SELECT ON ALL_CONSTRAINTS TO cdcuser;
GRANT SELECT ON ALL_CONS_COLUMNS TO cdcuser;
GRANT SELECT ON ALL_TAB_COLS TO cdcuser;
GRANT SELECT ON ALL_IND_COLUMNS TO cdcuser;
GRANT SELECT ON ALL_ENCRYPTED_COLUMNS TO cdcuser;
GRANT SELECT ON ALL_LOG_GROUPS TO cdcuser;
GRANT SELECT ON ALL_TAB_PARTITIONS TO cdcuser;
GRANT SELECT ON SYS.DBA_REGISTRY TO cdcuser;
GRANT SELECT ON SYS.OBJ$ TO cdcuser;
GRANT SELECT ON DBA_TABLESPACES TO cdcuser;
GRANT SELECT ON DBA_OBJECTS TO cdcuser;
GRANT SELECT ON SYS.ENC$ TO cdcuser;

-- 4. LogMiner 권한
GRANT EXECUTE ON DBMS_LOGMNR TO cdcuser;
GRANT EXECUTE ON DBMS_LOGMNR_D TO cdcuser;
GRANT SELECT ON V_$LOGMNR_LOGS TO cdcuser;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO cdcuser;

-- 5. mesuser 테이블 읽기 권한
GRANT SELECT ON MESUSER.PRODUCT TO cdcuser;
GRANT SELECT ON MESUSER.PRODUCTION_ORDER TO cdcuser;
GRANT SELECT ON MESUSER.ORDER_DETAIL TO cdcuser;
GRANT SELECT ON MESUSER.INVENTORY TO cdcuser;
GRANT SELECT ON MESUSER.PRODUCTION_HISTORY TO cdcuser;
GRANT SELECT ON MESUSER.PRODUCT_DOCUMENT TO cdcuser;
GRANT SELECT ON MESUSER.PRODUCT_SPEC TO cdcuser;
GRANT SELECT ON MESUSER.DAILY_SUMMARY TO cdcuser;
GRANT SELECT ON MESUSER.TEST_PRODUCT TO cdcuser;

-- 6. 확인
SELECT * FROM DBA_USERS WHERE USERNAME = 'CDCUSER';

EXIT;
