-- 사용자가 이미 존재하면 삭제
BEGIN
    EXECUTE IMMEDIATE 'DROP USER mesuser CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

-- MES 사용자 생성
CREATE USER mesuser IDENTIFIED BY mespass
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- 권한 부여
GRANT CONNECT, RESOURCE TO mesuser;
GRANT CREATE VIEW TO mesuser;
GRANT CREATE MATERIALIZED VIEW TO mesuser;
GRANT CREATE DATABASE LINK TO mesuser;
GRANT CREATE SEQUENCE TO mesuser;
GRANT CREATE TRIGGER TO mesuser;
GRANT CREATE PROCEDURE TO mesuser;
GRANT CREATE TYPE TO mesuser;

EXIT;
